name: Run tests
on:
  pull_request:
    types: [labeled]
  schedule:
  - cron:  '0 */6 * * *'
env:
  GO111MODULE: on

jobs:

  stub:
    name: Greeting
    runs-on: ubuntu-latest
    steps:

    - name: Greeting
      run: echo "This job is used to prevent the workflow to fail when all other jobs are skipped."

  unlabel:
    name: Unlabel
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.label.id == 1745044226 # execute tests label
    steps:

    - uses: actions/github-script@0.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.removeLabel({...context.issue, name: '${{github.event.label.name}}'})

  compile_test_binaries:
    name: Compile test binaries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'schedule' || (github.event_name == 'pull_request' && github.event.label.id == 1745044226) # execute tests label
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Download go modules
      run: go mod download
      shell: bash

    - name: Compile test binaries
      run: |
        # unit test binaries
        ./scripts/tests/precompilied_test_binaries.sh ./cmd ./precompiled_test_binaries/unit/cmd
        ./scripts/tests/precompilied_test_binaries.sh ./pkg ./precompiled_test_binaries/unit/pkg

        # integration test binaries
        ./scripts/tests/precompilied_test_binaries.sh ./integration ./precompiled_test_binaries/integration --tags integration

        # integration_k8s test binaries
        ./scripts/tests/precompilied_test_binaries.sh ./integration ./precompiled_test_binaries/integration_k8s --tags integration_k8s

        # werf with coverage binary
        ./scripts/tests/werf_with_coverage.sh
      shell: bash

    - name: Upload unit test binaries
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_unit_test_binaries"
        path: precompiled_test_binaries/unit

    - name: Upload integration test binaries
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_integration_test_binaries"
        path: precompiled_test_binaries/integration

    - name: Upload integration k8s test binaries
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_integration_k8s_test_binaries"
        path: precompiled_test_binaries/integration_k8s

    - name: Upload werf with coverage binary
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_werf_with_coverage"
        path: bin/tests/werf_with_coverage
      if: matrix.os != 'windows-latest'

    - name: Upload werf with coverage binary
      uses: actions/upload-artifact@master
      with:
        name: "${{ matrix.os }}_werf_with_coverage"
        path: bin/tests/werf_with_coverage.exe
      if: matrix.os == 'windows-latest'

  unit_tests:
    name: Unit tests
    needs: compile_test_binaries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Download unit binaries
      uses: actions/download-artifact@master
      with:
        name: "${{ matrix.os }}_unit_test_binaries"
        path: unit

    - name: Prepare environment
      run: |
        export WERF_TEST_COVERAGE_DIR=$GITHUB_WORKSPACE/tests_coverage/unit_tests/${{ matrix.os }}
        mkdir -p $WERF_TEST_COVERAGE_DIR
        echo ::set-env name=WERF_TEST_COVERAGE_DIR::$WERF_TEST_COVERAGE_DIR
      shell: bash

    - name: Test
      run:
        for test_binary in $(find unit -type f -name '*.test' ); do
          filename=$(echo $test_binary | tr / _)_coverage.out
          $test_binary -test.coverprofile=$WERF_TEST_COVERAGE_DIR/$filename
        done
      shell: bash

    - name: Upload coverage artifact
      uses: actions/upload-artifact@master
      with:
        name: tests_coverage
        path: tests_coverage
